REBOL []

do %webgoo/refaktor-utils.r
redo: does [ do %gen-scripts.r ]
fix-braces: func [ x ] [ replace/all replace/all x "(((" "{" ")))" "}" ]
varname: func [ k ] [ join uppercase to-string k "VAL" ]

D: load %definitions.r

gen: func [ d /local x r ] [

; ===

fix-braces rejoin [ {#!/usr/bin/bash

#generated by gen-scripts.r defined by definitions.r

usage()
(((
cat <<EOF

usage: $0 options

} d/descr {

options:
} 
(accumulate [k v] acc "" d/options [ 
	    reform 
	    [ acc  join "-" k v/1 (either found? find v 'r ["(required)"]["(optional)"]) newline ]
]) {
EOF

)))

}

(accumulate [k v] acc "" d/options [ 
	    rejoin 
	    [ acc (varname k) "=" (either none? x: select v 'def [""][ join3 {"} x  {"} ]) newline ]
]) {

while getopts h}

(accumulate [k v] acc "" d/options [ 
	    rejoin 
	    [ acc  k (either found? find v 'v [":"][":"]) ]])

{ OPTION
do
	case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
}

(accumulate [k v] acc "" d/options [ 
	    join acc either found? find v 'v [ 
	    	   rejoin 
	    	    [ 	  tab tab k ")" newline 
		          tab tab tab (varname k) "=$OPTARG" newline 
			  tab tab tab ";;" newline ]
	    ] [ "" ]])

{	?)
	    usage
	    exit
	    ;;
    esac
done
}

(either empty? x: (accumulate [k v] acc "" d/options [ 
	    join acc either found? find v 'r [
	    	    rejoin 
	    	    [  (either empty? acc [""][" || "]) 
		       "[[ -z $" varname k  " ]]"
		    ]
	] [ "" ]]) 
[ "" ]
[ rejoin [ 

{
if } x {
then

     usage
     cat <<EOF 

 - One or more of required params are missing.
EOF
     exit 1
fi
} ] ])

{

curl -k \
     -u `cat .invfpwd`:x \
     -d "}

(accumulate [k v] acc "" d/options [ 
	    join acc either all [ x: select v 'v  not equal? first to-string x #"_" ] [
	    	    rejoin
	    	    [  (either empty? acc [""]["&"]) 
		       x "=${" varname k  "}"
		    ]
	] [ "" ]])

{" \
     "https://www.cebelca.biz/API?_r=} d/resource {&_m=} d/method 
(either found? find d/options 'f ["&_f=${FVAL}"][""]) {"}





]
]


forskip D 2 [
	write x: join %invf- first D gen second D
	print join "- generated " x
]
print "=done"
halt