#!/bin/bash
#
##
### Čebelca.biz primeri (novi strežnik z davčnimi blagajnami)
##
#
# namen: predstaviti osnovne, mogoče za API niti ne optimalne ukaze Čebelca.biz API-ja
# če potrebujete primer lahko pogledate kako stvari dela spletna aplikacija, saj uporablja isti api
# pripravljamo pa tudi "api-explorer" in uradno dokumentacijo. Oboje pride ven, ko uradno izdamo API 
# (to bo ko naredimo da bo možno generirati več api ključev, jim določiti pravice in jih zakleniti na IP)
#
# pred pričetkom v datoteko .token vpišite Čebelca.biz API ključ
#
# ukaze pokličete npr. tako:
#
# ./curl-samples.bash r1 12
#

TOKEN=`cat .token`
CMD=$1
ARG=$2
ARG2=$3

#
## naredimo get zahtevo na Čebelca API
#

if [[ $CMD == "r0a" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	"http://test.cebelca.biz/API?_r=invoice-sent&_m=insert-into"
fi
# 401 only http post allowed

#
## naredimo post zahtevo 
#

if [[ $CMD == "r0b" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "" \
	"http://test.cebelca.biz/API?_r=invoice-sent&_m=insert-into"
fi
# 403 dobimo napako validacije z podatki o tem kaj je narobe v JSON obliki


## naredimo post zahtevo, z enim podatkom 

if [[ $CMD == "r0c" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "date_sent=12.12.2015" \
	"http://test.cebelca.biz/API?_r=invoice-sent&_m=insert-into"
fi
# dobimo validacijske napake v JSON obliki, eno manj

# zagotovimo partnerja (če točno tak že obstaja pridobi ID partnerja, će še ne ga doda in pridobi ID partnerja)

if [[ $CMD == "p1" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "name=My Company&street=Downing street&postal=E1w201&city=London" \
	"http://test.cebelca.biz/API?_r=partner&_m=assure"

fi
#>> ['ok',[{'id':1}]]


#
## dodajmo galvo računa na osnovni način
#

if [[ $CMD == "r1" && $ARG != "" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "date_sent=22.12.2015&date_to_pay=30.12.2015&date_served=22.12.2015&id_partner=$ARG" \
	"http://test.cebelca.biz/API?_r=invoice-sent&_m=insert-into"

fi
#>> ['ok',[{'id':1}]] 

#
## dodajmo postavko v račun . paramaeter $2 mora vsebovati ID glave računa (rezultat prejšnje zahteve) 
#

if [[ $CMD == "rb1" && $ARG != "" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "title=programming service&qty=10&mu=piece&price=120&vat=20&discount=0&id_invoice_sent=$ARG" \
	"http://test.cebelca.biz/API?_r=invoice-sent-b&_m=insert-into"

fi

#
## določimo da je račun delno plačan
#

if [[ $CMD == "rp1" && $ARG != "" && $ARG2 != "" ]]; then

    curl -v -k \
	-u $TOKEN:x \
	-d "date_of=22.12.2015&amount=10&id_payment_method=$ARG2&id_invoice_sent=$ARG" \
	"http://test.cebelca.biz/API?_r=invoice-sent-p&_m=insert-into"

fi

# prenesemo PDF računa

if [[ $CMD == "pdf" && ARG != "" ]]; then

    curl -v -k \
	-u $TOKEN:x -J -O \
	"http://test.cebelca.biz/API-pdf?id=$ARG&format=PDF&doctitle=Ra%C4%8Dun%20%C5%A1t.&lang=si&disposition=inline&res=invoice-sent&preview=0"
fi
#>> binary-pdf-data
